@startuml
class RegionProposal {

{static} +get_region_proposals() : List[BoundingBox]
{static} -format_box() : BoundingBox
}


class StyleGAN2Ada {
-paper_256_cfg : EasyDict
-common_kwargs : EasyDict
-gen_kwargs : EasyDict 
-dis_kwargs: EasyDict

+generator: Generator
+discriminator: Discriminator
+generator_copy: Generator
+vgg16: ScriptModule

+project_image(): Tensor
+get_image_and_features(): Tuple[Tensor, Tensor]
}

class Predictor {
+beast: String
+projector: StyleGAN2Ada
+few_shot: FewShotCNN
+classes: List[String]
+classifier: Classifier

-feature_vector: namedtuple

+predict_beast(): String
+get_region_suggestions(): List[BoundingBox]
+process_regions(): List[np.ndarray]
+crop_image(): np.ndarray
+project_to_latent(): List[ImageColletion]
+get_features(): Tuple
+select_regions(): Tuple
+predict_class(): String
+filter_predictions(): List[ClassPrediction]
}
@enduml